//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOOTechservice
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;

    public partial class Tasks
    {
        public int id_task { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_progress { get; set; }
    
        public virtual Progress Progress { get; set; }
        public virtual Users Users { get; set; }

        public static implicit operator Task(Tasks v)
        {
            throw new NotImplementedException();
        }
    }
}
